### PR TITLE
Recipe Details

### LINKED ISSUE #101: display error message when user's choices are contradictory and unsupported by the edamam API
currently, if the user is trying to filter recipes by a wide range of diets and health labels that could be contradictory (ex: vegan  in profile but search for chicken), it leads to bad request, and the search page will remain blank. A more friendly user interface could display the error message to let users know the problem.

### LINKED ISSUE #148: Refactor: Build recipe details into new client
# Tasks
- [x] Display select recipe in details view

### LINKED ISSUE #150: Refactor: Hook add favorites logic into new client
# Tasks
- [x] Allow user to add recipes to favorites when logged in
- [x] Show error to user when not logged in
- [x] Remove recipe from user favorites

### LINKED ISSUE #151: Feature: Build user profile page
# Tasks
- [x] Display user profile info
- [x] Allow user to update first name and last name
- [x] Allow user to update password
- [x] Allow user to update email

### LINKED ISSUE #153: Feature: Build about us page
# Tasks
- [x] Add detailed information to about us page

### PR DESCRIPTION
**Pull request by Thompson632**
Closes #148 
Closes #150 
Closes #101 
Closes #153 
Closes #151

### CODE REVIEW

**Review by nicksonsini97 — APPROVED** [review]
That looks good to me, I may have to update some stuff on the app end when I merge but this looks good

**Comment by Thompson632** [comment]
> That looks good to me, I may have to update some stuff on the app end when I merge but this looks good

You _may_ need to but I verified functionality with the existing legacy app to verify it works and it did... only major server change i made was moving the edamam endpoints about the user auth so we can search without needing to be logged in

**Comment by nicksonsini97** [comment]
> > That looks good to me, I may have to update some stuff on the app end when I merge but this looks good
> 
> You _may_ need to but I verified functionality with the existing legacy app to verify it works and it did... only major server change i made was moving the edamam endpoints about the user auth so we can search without needing to be logged in

Sweet that sounds good!

**Review by nicksonsini97 — APPROVED** [review]
Still all looks good to me. Nice work on this!

**Pull request merged**
